version: '0.2'
language: en
dictionaries:
  - css
  - html
  - typescript
enableFiletypes:
  - ignore
  - properties
  - svelte
  - xml
files:
  - '**/.*'
  - '**/*.{css,js,json,jsonc,html,md,scss,svelte,svg,yaml,yml,xml}'
useGitignore: true
ignorePaths:
  - pnpm-lock.yaml
  - content/**
  - scripts/build-blog.js
  - data/**/*.json
  - package/**
  - src/**/*.test.js
  - src/lib/locales/*.yaml
  - '!src/lib/locales/en-*.yaml'
words:
  - analyzing
  - agua
  - Agua
  - appinstalled
  - archivos
  - Artículo
  - Artículos
  - artículos
  - astrolicious
  - astros
  - automáticamente
  - autohospedado
  - Backblaze
  - backlink
  - backlinks
  - beforeinstallprompt
  - brotlied
  - BYOK
  - camelcase
  - Cloudinary
  - Configuración
  - Contenido
  - cmaps
  - Codeberg
  - cooldown
  - cuenta
  - CVEs
  - danurbanowicz
  - Decap
  - DeepL
  - deepmerge
  - DeepSeek
  - desde
  - Descripción
  - devfanatic
  - dialogs
  - dompurify
  - embeddable
  - editores
  - esbuild
  - estilos
  - exif
  - exifr
  - Fecha
  - FedRAMP
  - Flavored
  - Forgejo
  - frontmatter
  - GHSA
  - Ghsas
  - gestión
  - gitdir
  - Gitea
  - Hermanos
  - hermanos
  - goldmark
  - groupable
  - guardan
  - hotlinking
  - hugolify
  - husenunicorn
  - iarna
  - iccs
  - IIFE
  - indexeddb
  - Imágenes
  - infobar
  - infobars
  - inician
  - jfif
  - jsdoc
  - jSquash
  - keymap
  - keyvalue
  - Kohei
  - kyoshino
  - llms
  - Lume
  - lvml
  - mdwn
  - messageformat
  - mkdn
  - monta
  - Mtei
  - Mullvad
  - notranslate
  - nvmrc
  - onkeydowncapture
  - onpastecapture
  - onwheelcapture
  - OPFS
  - oxlint
  - parseable
  - passwordless
  - pexels
  - Photoshop
  - Picsum
  - Pixabay
  - PKCE
  - plusplus
  - pnpm
  - popups
  - postcss
  - prefs
  - previewable
  - privatemaker
  - programmatically
  - proxified
  - proxify
  - publicados
  - qrcode
  - Ragdoll
  - rearchitect
  - Redirigiendo
  - rebranded
  - reimagined
  - repositorio
  - requiere
  - rescanning
  - Roadmap
  - safesearch
  - sandboxing
  - sesión
  - Scaleway
  - sebousan
  - Shiki
  - sindresorhus
  - singleline
  - slugification
  - slugified
  - slugifying
  - smol
  - Sonda
  - strikethrough
  - stylelint
  - subfolders
  - subidos
  - Supabase
  - sveltejs
  - Sveltia
  - templatized
  - Título
  - Typecheck
  - unadded
  - unflatten
  - unflattened
  - unflattening
  - unlinkable
  - unlocalised
  - unlocalized
  - unpatched
  - unproxify
  - unrs
  - unsubscribers
  - vars
  - Uploadcare
  - videoseries
  - Vite
  - Vitest
  - WCAG
  - weba
  - webformat
  - whitespaces
  - worktree
  - xhigh
  - xslx
  - yacosta
  - Yoshino
  - zanhk
  - Zola
overrides:
  - language: en-gb
    filename: '**/*.md'
  - language: en-gb
    filename: src/lib/locales/en-{CA,GB}.yaml
